# Generated by Django 5.2.6 on 2025-09-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del equipo', max_length=200)),
                ('tipo', models.CharField(choices=[('servidor', 'Servidor'), ('pc', 'PC de escritorio'), ('portatil', 'Laptop'), ('monitor', 'Monitor'), ('impresora', 'Impresora'), ('otro', 'Otro')], max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(help_text='Número de serie único', max_length=150, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('serial', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='inventario.equipo')),
            ],
        ),
    ]
