# Generated by Django 5.2.6 on 2025-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
